package deploy

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"strings"
)

const (
	containerdConfigPath       = "/etc/containerd/config.toml"
	containerdProxyEnvPath     = "/etc/casos/containerd-proxy.env"
	containerdEgressDropInPath = "/etc/systemd/system/containerd.service.d/20-casos-egress.conf"

	generatedContainerdConfigMarker = "# Generated by CasOS"
	generatedContainerdEgressMarker = "# Generated by CasOS"
)

type containerdFileKind string

const (
	containerdFileAbsent    containerdFileKind = "absent"
	containerdFileManaged   containerdFileKind = "managed"
	containerdFileUnmanaged containerdFileKind = "unmanaged"
)

type containerdNoProxyInput struct {
	WorkerHosts []string
	APIServer   string
	DirectHosts []string
	ServiceCIDR string
}

type containerdFileSpec struct {
	Path             string
	Content          string
	Mode             string
	Present          bool
	BlockIfUnmanaged bool
	Legacy           []string
}

type containerdFileSnapshot struct {
	Kind    containerdFileKind
	Content string
	Mode    string
}

type containerdFileChange struct {
	Spec   containerdFileSpec
	Before containerdFileSnapshot
}

type containerdReconcileOptions struct {
	SandboxImage     string
	ConfigAdoption   containerdConfigAdoptionDecision
	ProxyExpectation containerdProxyExpectation
	Warn             func(string)
}

type containerdRetrySafeError struct {
	err error
}

func (e *containerdRetrySafeError) Error() string {
	return e.err.Error()
}

func (e *containerdRetrySafeError) Unwrap() error {
	return e.err
}

type containerdLifecycleRunner interface {
	InspectFileContext(ctx context.Context, path string) (containerdFileSnapshot, error)
	WriteFileAtomicContext(ctx context.Context, path, content, mode string) error
	RemoveFileContext(ctx context.Context, path string) error
	RunRootContext(ctx context.Context, command string) (string, error)
	RunRootSensitiveContext(ctx context.Context, command string) (string, error)
	VerifyContainerdImagePullCRIContext(ctx context.Context, image string) error
}

func renderContainerdEgressDropIn() string {
	return generatedContainerdEgressMarker + `
[Service]
EnvironmentFile=-/etc/casos/containerd-proxy.env
`
}

func renderContainerdProxyEnv(proxyURL string, noProxy []string) (string, error) {
	proxyURL = strings.TrimSpace(proxyURL)
	if proxyURL == "" {
		return "", fmt.Errorf("containerd proxy URL is required")
	}
	if strings.ContainsAny(proxyURL, "\x00\r\n") {
		return "", fmt.Errorf("containerd proxy URL contains an invalid control character")
	}
	parsed, err := url.Parse(proxyURL)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return "", fmt.Errorf("invalid containerd proxy URL")
	}
	switch strings.ToLower(parsed.Scheme) {
	case "http", "https", "socks5", "socks5h":
	default:
		return "", fmt.Errorf("unsupported containerd proxy scheme %q", parsed.Scheme)
	}

	for _, entry := range noProxy {
		if strings.ContainsAny(entry, "\x00\r\n") {
			return "", fmt.Errorf("containerd NO_PROXY contains an invalid control character")
		}
	}
	noProxyValue := strings.Join(stableUniqueNonEmpty(noProxy), ",")
	return fmt.Sprintf(`%s
HTTP_PROXY=%s
HTTPS_PROXY=%s
ALL_PROXY=""
NO_PROXY=%s
http_proxy=%s
https_proxy=%s
all_proxy=""
no_proxy=%s
`, generatedContainerdEgressMarker,
		quoteSystemdEnvironmentValue(proxyURL),
		quoteSystemdEnvironmentValue(proxyURL),
		quoteSystemdEnvironmentValue(noProxyValue),
		quoteSystemdEnvironmentValue(proxyURL),
		quoteSystemdEnvironmentValue(proxyURL),
		quoteSystemdEnvironmentValue(noProxyValue)), nil
}

func quoteSystemdEnvironmentValue(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, `"`, `\"`)
	return `"` + value + `"`
}

func redactProxyURL(raw string) string {
	parsed, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || parsed.Host == "" {
		return "[redacted proxy URL]"
	}
	if parsed.User != nil {
		if _, hasPassword := parsed.User.Password(); hasPassword {
			parsed.User = url.UserPassword("***", "***")
		} else {
			parsed.User = url.User("***")
		}
	}
	return parsed.String()
}

func buildContainerdNoProxy(input containerdNoProxyInput) []string {
	values := []string{
		"localhost",
		"127.0.0.1",
		"::1",
		".svc",
		".cluster.local",
		nodeDeployClusterCIDR,
		input.ServiceCIDR,
	}
	values = append(values, input.WorkerHosts...)
	if parsed, err := url.Parse(strings.TrimSpace(input.APIServer)); err == nil && parsed.Hostname() != "" {
		values = append(values, parsed.Hostname())
	}
	values = append(values, input.DirectHosts...)
	return stableUniqueNonEmpty(values)
}

func buildContainerdDesiredFilesForRuntime(
	config Config,
	routing registryRoutingSelection,
	proxyURL string,
	workerHosts []string,
	apiserverURL string,
	runtimeVersion containerdRuntimeVersion,
) ([]containerdFileSpec, []string, error) {
	proxyEnabled := strings.TrimSpace(proxyURL) != ""
	var noProxy []string
	proxyEnv := ""
	if proxyEnabled {
		noProxy = buildContainerdNoProxy(containerdNoProxyInput{
			WorkerHosts: workerHosts,
			APIServer:   apiserverURL,
			DirectHosts: routing.directHosts(),
			ServiceCIDR: config.ServiceCIDR,
		})
		var err error
		proxyEnv, err = renderContainerdProxyEnv(proxyURL, noProxy)
		if err != nil {
			return nil, nil, err
		}
	}
	containerdConfig, err := generateContainerdConfigForRuntime(config.SandboxImage, runtimeVersion)
	if err != nil {
		return nil, nil, err
	}
	desired := []containerdFileSpec{
		{
			Path:    containerdConfigPath,
			Content: containerdConfig,
			Mode:    "0644",
			Present: true,
		},
		{
			Path:    containerdProxyEnvPath,
			Content: proxyEnv,
			Mode:    "0600",
			Present: proxyEnabled,
		},
		{
			Path:    containerdEgressDropInPath,
			Content: renderContainerdEgressDropIn(),
			Mode:    "0644",
			Present: proxyEnabled,
		},
		{
			Path:             dockerHubHostsPath,
			Content:          generateDockerHubMirrorOnlyHostsToml(),
			Mode:             "0644",
			Present:          routing.DockerHub.MirrorEnabled,
			BlockIfUnmanaged: routing.DockerHub.MirrorEnabled,
			Legacy:           []string{legacyDockerHubHostsToml()},
		},
		{
			Path:             k8sRegistryHostsPath,
			Content:          generateK8sRegistryMirrorOnlyHostsToml(),
			Mode:             "0644",
			Present:          routing.Kubernetes.MirrorEnabled,
			BlockIfUnmanaged: routing.Kubernetes.MirrorEnabled,
			Legacy:           []string{legacyK8sRegistryHostsToml()},
		},
	}
	return desired, noProxy, nil
}

func discoverContainerdWorkerHosts(
	ctx context.Context,
	runner interface {
		RunRootContext(context.Context, string) (string, error)
	},
) ([]string, error) {
	output, err := runner.RunRootContext(ctx, `set -e
hostname
hostname -f 2>/dev/null || true
hostname -I 2>/dev/null || true`)
	if err != nil {
		return nil, fmt.Errorf("discover worker hostname and addresses: %w", err)
	}
	hosts := stableUniqueNonEmpty(strings.Fields(output))
	for _, host := range hosts {
		if strings.ContainsAny(host, ",\x00\r\n") {
			return nil, fmt.Errorf("worker identity contains an invalid character")
		}
	}
	if len(hosts) == 0 {
		return nil, fmt.Errorf("worker hostname and addresses are empty")
	}
	return hosts, nil
}

func reconcileContainerdFiles(ctx context.Context, runner containerdLifecycleRunner, desired []containerdFileSpec, options containerdReconcileOptions) error {
	if runner == nil {
		return fmt.Errorf("containerd lifecycle runner is required")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	current := make(map[string]containerdFileSnapshot, len(desired))
	for _, file := range desired {
		if !isAllowedNodeDeployPath(file.Path) {
			return fmt.Errorf("unsupported containerd managed path: %s", file.Path)
		}
		snapshot, err := runner.InspectFileContext(ctx, file.Path)
		if err != nil {
			return fmt.Errorf("inspect %s: %w", file.Path, err)
		}
		current[file.Path] = snapshot
	}

	changes, warnings, err := planContainerdFiles(desired, current, options.ConfigAdoption)
	for _, warning := range warnings {
		if options.Warn != nil {
			options.Warn(warning)
		}
	}
	if err != nil {
		return err
	}
	if len(changes) == 0 {
		if _, err := runner.RunRootContext(ctx, "set -e; systemctl enable containerd >/dev/null; systemctl is-active --quiet containerd || systemctl start containerd"); err != nil {
			return fmt.Errorf("ensure containerd is active: %w", err)
		}
		if err := verifyContainerd(ctx, runner, options.SandboxImage, options.ProxyExpectation); err != nil {
			return &containerdRetrySafeError{err: err}
		}
		return nil
	}

	applied := make([]containerdFileChange, 0, len(changes))
	for _, change := range changes {
		attempted := append(applied, change)
		var err error
		if change.Spec.Present {
			err = runner.WriteFileAtomicContext(ctx, change.Spec.Path, change.Spec.Content, change.Spec.Mode)
		} else {
			err = runner.RemoveFileContext(ctx, change.Spec.Path)
		}
		if err != nil {
			return rollbackContainerdChanges(ctx, runner, attempted, false, false,
				fmt.Errorf("apply containerd file %s: %w", change.Spec.Path, err))
		}
		applied = attempted
	}

	dropInChanged := containerdDropInChanged(changes)
	if _, err := runner.RunRootContext(ctx, containerdConfigValidationCommand(dropInChanged)); err != nil {
		return rollbackContainerdChanges(ctx, runner, applied, false, false,
			fmt.Errorf("validate containerd configuration: %w", err))
	}
	if dropInChanged {
		if _, err := runner.RunRootContext(ctx, "systemctl daemon-reload"); err != nil {
			return rollbackContainerdChanges(ctx, runner, applied, true, false,
				fmt.Errorf("reload systemd: %w", err))
		}
	}
	if _, err := runner.RunRootContext(ctx, "systemctl enable containerd >/dev/null && systemctl restart containerd"); err != nil {
		return rollbackContainerdChanges(ctx, runner, applied, dropInChanged, true,
			fmt.Errorf("restart containerd: %w", err))
	}
	if err := verifyContainerd(ctx, runner, options.SandboxImage, options.ProxyExpectation); err != nil {
		return rollbackContainerdChanges(ctx, runner, applied, dropInChanged, true, err)
	}
	return nil
}

func containerdDropInChanged(changes []containerdFileChange) bool {
	for _, change := range changes {
		if change.Spec.Path == containerdEgressDropInPath {
			return true
		}
	}
	return false
}

func rollbackContainerdChanges(
	ctx context.Context,
	runner containerdLifecycleRunner,
	applied []containerdFileChange,
	reloadSystemd bool,
	restartContainerd bool,
	trigger error,
) error {
	if len(applied) == 0 {
		return fmt.Errorf("containerd reconciliation failed: %w", trigger)
	}

	rollbackCtx := context.WithoutCancel(ctx)
	var restoreErrors []error
	for i := len(applied) - 1; i >= 0; i-- {
		change := applied[i]
		var err error
		if change.Before.Kind == containerdFileAbsent {
			err = runner.RemoveFileContext(rollbackCtx, change.Spec.Path)
		} else {
			err = runner.WriteFileAtomicContext(rollbackCtx, change.Spec.Path, change.Before.Content, change.Before.Mode)
		}
		if err != nil {
			restoreErrors = append(restoreErrors, fmt.Errorf("restore %s: %w", change.Spec.Path, err))
		}
	}

	var reloadErr error
	if reloadSystemd {
		if _, err := runner.RunRootContext(rollbackCtx, "systemctl daemon-reload"); err != nil {
			reloadErr = fmt.Errorf("reload restored containerd systemd configuration: %w", err)
		}
	}
	var restartErr error
	if restartContainerd {
		if _, err := runner.RunRootContext(rollbackCtx, "systemctl restart containerd && systemctl is-active --quiet containerd"); err != nil {
			restartErr = fmt.Errorf("restart containerd with restored configuration: %w", err)
		}
	}

	reconciliationErrors := []error{trigger}
	reconciliationErrors = append(reconciliationErrors, restoreErrors...)
	reconciliationErrors = append(reconciliationErrors, reloadErr, restartErr)
	joined := errors.Join(reconciliationErrors...)
	if len(restoreErrors) > 0 {
		return fmt.Errorf("containerd reconciliation failed; one or more modified files could not be restored: %w", joined)
	}
	if restartErr != nil {
		return fmt.Errorf("containerd reconciliation failed; modified files were restored, but containerd could not be restarted with the restored configuration: %w", joined)
	}
	if reloadErr != nil {
		return fmt.Errorf("containerd reconciliation failed; modified files were restored, but the restored systemd configuration could not be reloaded: %w", joined)
	}
	return &containerdRetrySafeError{err: fmt.Errorf("containerd reconciliation failed; modified files were restored: %w", trigger)}
}
