package deploy

import (
	"context"
	"fmt"
	"strconv"
	"strings"
)

const generatedRegistryHostsMarker = "# Generated by CasOS"

type containerdRuntimeVersion struct {
	Major int
	Minor int
}

// GenerateContainerdConfig returns the containerd 2.x configuration used by
// the manual worker bootstrap API. Automated deployment detects the remote
// runtime and uses generateContainerdConfigForRuntime instead.
func GenerateContainerdConfig(sandboxImage string) string {
	return generateContainerd2Config(sandboxImage)
}

// GenerateContainerdConfigForVersion returns a manual bootstrap config for a
// caller-supplied containerd version. An empty version preserves the legacy
// API behavior and selects containerd 2.x.
func GenerateContainerdConfigForVersion(sandboxImage, rawVersion string) (string, error) {
	version, err := parseManualContainerdRuntimeVersion(rawVersion)
	if err != nil {
		return "", err
	}
	return generateContainerdConfigForRuntime(sandboxImage, version)
}

func parseManualContainerdRuntimeVersion(rawVersion string) (containerdRuntimeVersion, error) {
	value := strings.TrimPrefix(strings.ToLower(strings.TrimSpace(rawVersion)), "v")
	if value == "" {
		value = "2"
	}
	parts := strings.Split(value, ".")
	if len(parts) > 3 || len(parts) == 0 {
		return containerdRuntimeVersion{}, fmt.Errorf("cannot parse containerd version %q", rawVersion)
	}
	major, err := strconv.Atoi(parts[0])
	if err != nil {
		return containerdRuntimeVersion{}, fmt.Errorf("cannot parse containerd version %q", rawVersion)
	}
	version := containerdRuntimeVersion{Major: major}
	if len(parts) > 1 && parts[1] != "x" {
		version.Minor, err = strconv.Atoi(parts[1])
		if err != nil {
			return containerdRuntimeVersion{}, fmt.Errorf("cannot parse containerd version %q", rawVersion)
		}
	}
	if len(parts) > 2 {
		if parts[1] == "x" {
			return containerdRuntimeVersion{}, fmt.Errorf("cannot parse containerd version %q", rawVersion)
		}
		patchEnd := 0
		for patchEnd < len(parts[2]) && parts[2][patchEnd] >= '0' && parts[2][patchEnd] <= '9' {
			patchEnd++
		}
		if patchEnd == 0 {
			return containerdRuntimeVersion{}, fmt.Errorf("cannot parse containerd version %q", rawVersion)
		}
	}
	if version.Major == 1 && (len(parts) < 2 || parts[1] == "x") {
		return containerdRuntimeVersion{}, fmt.Errorf("containerd 1.x must specify version 1.6 or newer")
	}
	return version, nil
}

func generateContainerdConfigForRuntime(sandboxImage string, version containerdRuntimeVersion) (string, error) {
	switch version.Major {
	case 1:
		if version.Minor < 6 {
			return "", fmt.Errorf("containerd %d.%d is unsupported; version 1.6 or newer is required", version.Major, version.Minor)
		}
		return fmt.Sprintf(`# Generated by CasOS
version = 2

[plugins.'io.containerd.grpc.v1.cri']
  sandbox_image = %q

  [plugins.'io.containerd.grpc.v1.cri'.containerd.runtimes.runc]
    runtime_type = 'io.containerd.runc.v2'
    [plugins.'io.containerd.grpc.v1.cri'.containerd.runtimes.runc.options]
      SystemdCgroup = true

  [plugins.'io.containerd.grpc.v1.cri'.registry]
    config_path = '/etc/containerd/certs.d'
`, sandboxImage), nil
	case 2:
		return generateContainerd2Config(sandboxImage), nil
	default:
		return "", fmt.Errorf("containerd major version %d is unsupported", version.Major)
	}
}

func generateContainerd2Config(sandboxImage string) string {
	return fmt.Sprintf(`# Generated by CasOS
version = 3

[plugins.'io.containerd.cri.v1.images']
  [plugins.'io.containerd.cri.v1.images'.pinned_images]
    sandbox = %q

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc.options]
  SystemdCgroup = true

[plugins.'io.containerd.cri.v1.images'.registry]
  config_path = '/etc/containerd/certs.d'
`, sandboxImage)
}

func inspectContainerdRuntimeVersion(
	ctx context.Context,
	runner interface {
		RunRootContext(context.Context, string) (string, error)
	},
) (containerdRuntimeVersion, error) {
	output, err := runner.RunRootContext(ctx, "containerd --version")
	if err != nil {
		return containerdRuntimeVersion{}, fmt.Errorf("inspect containerd version: %w", err)
	}
	version, err := parseContainerdRuntimeVersion(output)
	if err != nil {
		return containerdRuntimeVersion{}, fmt.Errorf("inspect containerd version: %w", err)
	}
	return version, nil
}

func parseContainerdRuntimeVersion(output string) (containerdRuntimeVersion, error) {
	for _, field := range strings.Fields(output) {
		candidate := strings.TrimPrefix(field, "v")
		parts := strings.SplitN(candidate, ".", 3)
		if len(parts) != 3 {
			continue
		}
		major, err := strconv.Atoi(parts[0])
		if err != nil {
			continue
		}
		minor, err := strconv.Atoi(parts[1])
		if err != nil {
			continue
		}
		patchText := parts[2]
		patchEnd := 0
		for patchEnd < len(patchText) && patchText[patchEnd] >= '0' && patchText[patchEnd] <= '9' {
			patchEnd++
		}
		if patchEnd == 0 {
			continue
		}
		if _, err := strconv.Atoi(patchText[:patchEnd]); err != nil {
			continue
		}
		version := containerdRuntimeVersion{Major: major, Minor: minor}
		if _, err := generateContainerdConfigForRuntime("validation", version); err != nil {
			return containerdRuntimeVersion{}, err
		}
		return version, nil
	}
	return containerdRuntimeVersion{}, fmt.Errorf("cannot parse containerd version output")
}

// GenerateDockerHubHostsToml returns the content for
// /etc/containerd/certs.d/docker.io/hosts.toml. The canonical server remains
// the fallback when the mirror is unavailable.
func GenerateDockerHubHostsToml() string {
	return generatedRegistryHostsMarker + `
server = "https://registry-1.docker.io"

[host."https://docker.1ms.run"]
  capabilities = ["pull", "resolve"]
`
}

// GenerateK8sRegistryHostsToml returns the content for
// /etc/containerd/certs.d/registry.k8s.io/hosts.toml. The canonical server
// remains the fallback when the mirror is unavailable.
func GenerateK8sRegistryHostsToml() string {
	return generatedRegistryHostsMarker + `
server = "https://registry.k8s.io"

[host."https://registry.aliyuncs.com/v2/google_containers"]
  capabilities = ["pull", "resolve"]
  override_path = true
`
}

func generateDockerHubMirrorOnlyHostsToml() string {
	return generatedRegistryHostsMarker + `
server = "https://docker.1ms.run"
capabilities = ["pull", "resolve"]
`
}

func generateK8sRegistryMirrorOnlyHostsToml() string {
	return generatedRegistryHostsMarker + `
server = "https://registry.aliyuncs.com/v2/google_containers"
capabilities = ["pull", "resolve"]
override_path = true
`
}

func legacyDockerHubHostsToml() string {
	return `server = "https://registry-1.docker.io"

[host."https://docker.1ms.run"]
  capabilities = ["pull", "resolve"]
`
}

func legacyK8sRegistryHostsToml() string {
	return `server = "https://registry.k8s.io"

[host."https://registry.aliyuncs.com/google_containers"]
  capabilities = ["pull", "resolve"]
`
}
