package deploy

import (
	"context"
	"fmt"
	"net"
	"net/url"
	"strconv"
	"strings"
)

const (
	containerdConfigPath       = "/etc/containerd/config.toml"
	containerdProxyEnvPath     = "/etc/casos/containerd-proxy.env"
	containerdEgressDropInPath = "/etc/systemd/system/containerd.service.d/20-casos-egress.conf"
	nodeDeployServiceCIDR      = "10.43.0.0/16"

	generatedContainerdConfigMarker    = "# Generated by CasOS"
	generatedContainerdEgressMarker    = "# Generated by CasOS"
	defaultContainerdVerificationImage = "nginx:1.27.5-alpine"
)

type containerdFileKind string

const (
	containerdFileAbsent    containerdFileKind = "absent"
	containerdFileManaged   containerdFileKind = "managed"
	containerdFileUnmanaged containerdFileKind = "unmanaged"
)

type containerdFileAction string

const (
	containerdFileWrite  containerdFileAction = "write"
	containerdFileRemove containerdFileAction = "remove"
)

type containerdFileRole string

const (
	containerdFileRoleConfig       containerdFileRole = "config"
	containerdFileRoleProxyEnv     containerdFileRole = "proxy-env"
	containerdFileRoleProxyDropIn  containerdFileRole = "proxy-drop-in"
	containerdFileRoleRegistryHost containerdFileRole = "registry-hosts"
)

type containerdDesiredState string

const (
	containerdDesiredAbsent  containerdDesiredState = "absent"
	containerdDesiredPresent containerdDesiredState = "present"
)

type containerdNoProxyInput struct {
	WorkerHosts []string
	APIServer   string
	DirectHosts []string
	Additional  []string
}

type containerdDesiredFile struct {
	Path             string
	Role             containerdFileRole
	Content          string
	Mode             string
	State            containerdDesiredState
	BlockIfUnmanaged bool
	DaemonReload     bool
	Restart          bool
	Legacy           []string
}

type containerdFileSnapshot struct {
	Kind    containerdFileKind
	Content string
	Mode    string
}

type containerdFileChange struct {
	Path     string
	Action   containerdFileAction
	Content  string
	Mode     string
	Previous containerdFileSnapshot
}

type containerdFilePlan struct {
	Changes      []containerdFileChange
	Warnings     []string
	Blocked      []string
	DaemonReload bool
	Restart      bool
}

type containerdReconcileResult struct {
	Changed           bool
	Reloaded          bool
	Restarted         bool
	Verification      containerdVerificationResult
	Warnings          []string
	ChangedPaths      []string
	RolledBackFrom    error
	RollbackCompleted bool
}

type containerdLifecycleRunner interface {
	InspectFileContext(ctx context.Context, path string) (containerdFileSnapshot, error)
	WriteFileAtomicContext(ctx context.Context, path, content, mode string) error
	RemoveFileContext(ctx context.Context, path string) error
	RunRootContext(ctx context.Context, command string) (string, error)
}

func renderContainerdEgressDropIn() string {
	return generatedContainerdEgressMarker + `
[Service]
EnvironmentFile=-/etc/casos/containerd-proxy.env
`
}

func renderContainerdProxyEnv(proxyURL string, noProxy []string) (string, error) {
	proxyURL = strings.TrimSpace(proxyURL)
	if proxyURL == "" {
		return "", fmt.Errorf("containerd proxy URL is required")
	}
	if strings.ContainsAny(proxyURL, "\x00\r\n") {
		return "", fmt.Errorf("containerd proxy URL contains an invalid control character")
	}
	parsed, err := url.Parse(proxyURL)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return "", fmt.Errorf("invalid containerd proxy URL")
	}
	switch strings.ToLower(parsed.Scheme) {
	case "http", "https", "socks5", "socks5h":
	default:
		return "", fmt.Errorf("unsupported containerd proxy scheme %q", parsed.Scheme)
	}

	for _, entry := range noProxy {
		if strings.ContainsAny(entry, "\x00\r\n") {
			return "", fmt.Errorf("containerd NO_PROXY contains an invalid control character")
		}
	}
	noProxyValue := strings.Join(stableUniqueNonEmpty(noProxy), ",")
	return fmt.Sprintf(`%s
HTTP_PROXY=%s
HTTPS_PROXY=%s
NO_PROXY=%s
http_proxy=%s
https_proxy=%s
no_proxy=%s
`, generatedContainerdEgressMarker,
		quoteSystemdEnvironmentValue(proxyURL),
		quoteSystemdEnvironmentValue(proxyURL),
		quoteSystemdEnvironmentValue(noProxyValue),
		quoteSystemdEnvironmentValue(proxyURL),
		quoteSystemdEnvironmentValue(proxyURL),
		quoteSystemdEnvironmentValue(noProxyValue)), nil
}

func quoteSystemdEnvironmentValue(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, `"`, `\"`)
	return `"` + value + `"`
}

func redactProxyURL(raw string) string {
	parsed, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || parsed.Host == "" {
		return "[redacted proxy URL]"
	}
	if parsed.User != nil {
		if _, hasPassword := parsed.User.Password(); hasPassword {
			parsed.User = url.UserPassword("***", "***")
		} else {
			parsed.User = url.User("***")
		}
	}
	return parsed.String()
}

func buildContainerdNoProxy(input containerdNoProxyInput) []string {
	values := []string{
		"localhost",
		"127.0.0.1",
		"::1",
		".svc",
		".cluster.local",
		nodeDeployClusterCIDR,
		nodeDeployServiceCIDR,
	}
	values = append(values, input.WorkerHosts...)
	if parsed, err := url.Parse(strings.TrimSpace(input.APIServer)); err == nil && parsed.Hostname() != "" {
		values = append(values, parsed.Hostname())
	}
	values = append(values, input.DirectHosts...)
	values = append(values, input.Additional...)
	return stableUniqueNonEmpty(values)
}

func buildContainerdDesiredFiles(config Config, routing registryRoutingSelection, workerHosts []string) ([]containerdDesiredFile, []string, error) {
	apiServer := ""
	apiServerHost := strings.TrimSpace(config.AdvertiseAddress)
	if apiServerHost == "" {
		apiServerHost = strings.TrimSpace(config.ApiserverBind)
	}
	if apiServerHost != "" && config.ApiserverPort > 0 {
		apiServer = "https://" + net.JoinHostPort(apiServerHost, strconv.Itoa(config.ApiserverPort))
	}
	noProxy := buildContainerdNoProxy(containerdNoProxyInput{
		WorkerHosts: workerHosts,
		APIServer:   apiServer,
		DirectHosts: routing.directHosts(),
		Additional:  config.ContainerdNoProxy,
	})

	proxyEnabled := strings.TrimSpace(config.ContainerdProxy) != ""
	proxyEnv := ""
	if proxyEnabled {
		var err error
		proxyEnv, err = renderContainerdProxyEnv(config.ContainerdProxy, noProxy)
		if err != nil {
			return nil, nil, err
		}
	}
	desired := []containerdDesiredFile{
		{
			Path:    containerdConfigPath,
			Role:    containerdFileRoleConfig,
			Content: GenerateContainerdConfig(config.SandboxImage),
			Mode:    "0644",
			State:   containerdDesiredPresent,
			Restart: true,
		},
		{
			Path:    containerdProxyEnvPath,
			Role:    containerdFileRoleProxyEnv,
			Content: proxyEnv,
			Mode:    "0600",
			State:   desiredState(proxyEnabled),
			Restart: true,
		},
		{
			Path:         containerdEgressDropInPath,
			Role:         containerdFileRoleProxyDropIn,
			Content:      renderContainerdEgressDropIn(),
			Mode:         "0644",
			State:        desiredState(proxyEnabled),
			DaemonReload: true,
			Restart:      true,
		},
		{
			Path:             dockerHubHostsPath,
			Role:             containerdFileRoleRegistryHost,
			Content:          GenerateDockerHubHostsTomlWithResolve(routing.DockerHub.MirrorEnabled && !routing.DockerHub.CanonicalRequired),
			Mode:             "0644",
			State:            desiredState(routing.DockerHub.MirrorEnabled),
			BlockIfUnmanaged: routing.DockerHub.MirrorEnabled && !routing.DockerHub.CanonicalRequired,
			Legacy:           []string{legacyDockerHubHostsToml()},
		},
		{
			Path:             k8sRegistryHostsPath,
			Role:             containerdFileRoleRegistryHost,
			Content:          GenerateK8sRegistryHostsTomlWithResolve(routing.Kubernetes.MirrorEnabled && !routing.Kubernetes.CanonicalRequired),
			Mode:             "0644",
			State:            desiredState(routing.Kubernetes.MirrorEnabled),
			BlockIfUnmanaged: routing.Kubernetes.MirrorEnabled && !routing.Kubernetes.CanonicalRequired,
			Legacy:           []string{legacyK8sRegistryHostsToml()},
		},
	}
	return desired, noProxy, nil
}

func desiredState(enabled bool) containerdDesiredState {
	if enabled {
		return containerdDesiredPresent
	}
	return containerdDesiredAbsent
}

func registryRoutingRequiresRealPull(routing registryRoutingSelection) bool {
	return (routing.DockerHub.MirrorEnabled && !routing.DockerHub.CanonicalRequired) ||
		(routing.Kubernetes.MirrorEnabled && !routing.Kubernetes.CanonicalRequired)
}

func discoverContainerdWorkerHosts(
	ctx context.Context,
	runner interface {
		RunRootContext(context.Context, string) (string, error)
	},
) ([]string, error) {
	output, err := runner.RunRootContext(ctx, `set -e
hostname
hostname -f 2>/dev/null || true
hostname -I 2>/dev/null || true`)
	if err != nil {
		return nil, fmt.Errorf("discover worker hostname and addresses: %w", err)
	}
	hosts := stableUniqueNonEmpty(strings.Fields(output))
	for _, host := range hosts {
		if strings.ContainsAny(host, ",\x00\r\n") {
			return nil, fmt.Errorf("worker identity contains an invalid character")
		}
	}
	if len(hosts) == 0 {
		return nil, fmt.Errorf("worker hostname and addresses are empty")
	}
	return hosts, nil
}

func preflightContainerdEgress(ctx context.Context, runner registryMirrorFileRunner, routing registryRoutingSelection, proxyURL string) ([]string, error) {
	details := make([]string, 0, 6)
	for _, target := range registryRouteTargets {
		var decision registryRouteDecision
		switch target.namespace {
		case "docker.io":
			decision = routing.DockerHub
		case "registry.k8s.io":
			decision = routing.Kubernetes
		default:
			return details, fmt.Errorf("unsupported registry namespace %q", target.namespace)
		}
		if strings.TrimSpace(decision.RegistryHost) == "" {
			continue
		}
		var detail string
		var err error
		if decision.CanonicalRequired {
			canonicalProxy, err := proxyForRegistryRoute(decision.CanonicalRoute, proxyURL)
			if err != nil {
				return details, fmt.Errorf("preflight %s canonical route: %w", target.name, err)
			}
			detail, err = requireRegistryPath(ctx, runner, target.name+" canonical", target.canonicalURL, canonicalProxy)
			if err != nil {
				return details, err
			}
			details = append(details, fmt.Sprintf("%s canonical %s: %s", target.name, decision.CanonicalRoute, detail))
		}

		if !decision.MirrorEnabled {
			continue
		}
		mirrorProxy, err := proxyForRegistryRoute(decision.MirrorRoute, proxyURL)
		if err != nil {
			return details, fmt.Errorf("preflight %s mirror route: %w", target.name, err)
		}
		detail, err = requireRegistryPath(ctx, runner, target.name+" mirror", target.mirrorURL, mirrorProxy)
		if err != nil {
			return details, err
		}
		details = append(details, fmt.Sprintf("%s mirror %s: %s", target.name, decision.MirrorRoute, detail))
	}
	return details, nil
}

func proxyForRegistryRoute(route registryEgressRoute, proxyURL string) (string, error) {
	switch route {
	case registryEgressDirect:
		return "", nil
	case registryEgressProxy:
		if strings.TrimSpace(proxyURL) == "" {
			return "", fmt.Errorf("proxy route selected without containerdProxy")
		}
		return proxyURL, nil
	default:
		return "", fmt.Errorf("unsupported route %q", route)
	}
}

func requireRegistryPath(ctx context.Context, runner registryMirrorFileRunner, name, targetURL, proxyURL string) (string, error) {
	reachable, detail, err := probeRegistryPath(ctx, runner, targetURL, proxyURL)
	if err != nil {
		return "", fmt.Errorf("probe %s: %w", name, err)
	}
	if !reachable {
		return detail, fmt.Errorf("%s is unreachable (%s)", name, detail)
	}
	return detail, nil
}

func reconcileContainerdFiles(ctx context.Context, runner containerdLifecycleRunner, desired []containerdDesiredFile, sandboxImage, verificationImage string, requireRealPull bool) (containerdReconcileResult, error) {
	result := containerdReconcileResult{}
	if runner == nil {
		return result, fmt.Errorf("containerd lifecycle runner is required")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	current := make(map[string]containerdFileSnapshot, len(desired))
	for _, file := range desired {
		if !isAllowedNodeDeployPath(file.Path) {
			return result, fmt.Errorf("unsupported containerd managed path: %s", file.Path)
		}
		snapshot, err := runner.InspectFileContext(ctx, file.Path)
		if err != nil {
			return result, fmt.Errorf("inspect %s: %w", file.Path, err)
		}
		current[file.Path] = snapshot
	}

	plan := planContainerdFiles(desired, current)
	result.Warnings = append(result.Warnings, plan.Warnings...)
	if len(plan.Blocked) > 0 {
		return result, fmt.Errorf("containerd desired state is blocked: %s", strings.Join(plan.Blocked, "; "))
	}
	applied := make([]containerdFileChange, 0, len(plan.Changes))
	rollback := func(trigger error) error {
		if len(applied) > 0 {
			result.RolledBackFrom = trigger
		}
		rollbackCtx := context.WithoutCancel(ctx)
		var rollbackErrors []string
		for i := len(applied) - 1; i >= 0; i-- {
			change := applied[i]
			var err error
			if change.Previous.Kind == containerdFileAbsent {
				err = runner.RemoveFileContext(rollbackCtx, change.Path)
			} else {
				err = runner.WriteFileAtomicContext(rollbackCtx, change.Path, change.Previous.Content, change.Previous.Mode)
			}
			if err != nil {
				rollbackErrors = append(rollbackErrors, fmt.Sprintf("restore %s: %v", change.Path, err))
			}
		}
		if plan.DaemonReload {
			if _, err := runner.RunRootContext(rollbackCtx, "systemctl daemon-reload"); err != nil {
				rollbackErrors = append(rollbackErrors, fmt.Sprintf("daemon-reload: %v", err))
			}
		}
		if plan.Restart {
			if _, err := runner.RunRootContext(rollbackCtx, "systemctl restart containerd"); err != nil {
				rollbackErrors = append(rollbackErrors, fmt.Sprintf("restart containerd: %v", err))
			}
		}
		if len(rollbackErrors) > 0 {
			return fmt.Errorf("%w (rollback errors: %s)", trigger, strings.Join(rollbackErrors, "; "))
		}
		result.RollbackCompleted = len(applied) > 0
		return trigger
	}

	for _, change := range plan.Changes {
		applied = append(applied, change)
		var err error
		switch change.Action {
		case containerdFileWrite:
			err = runner.WriteFileAtomicContext(ctx, change.Path, change.Content, change.Mode)
		case containerdFileRemove:
			err = runner.RemoveFileContext(ctx, change.Path)
		default:
			err = fmt.Errorf("unsupported file action %q", change.Action)
		}
		if err != nil {
			return result, rollback(fmt.Errorf("apply %s to %s: %w", change.Action, change.Path, err))
		}
		result.ChangedPaths = append(result.ChangedPaths, change.Path)
	}
	result.Changed = len(applied) > 0

	if result.Changed {
		if _, err := runner.RunRootContext(ctx, containerdConfigValidationCommand(plan.DaemonReload)); err != nil {
			return result, rollback(fmt.Errorf("validate containerd configuration: %w", err))
		}
	}
	if plan.DaemonReload {
		if _, err := runner.RunRootContext(ctx, "systemctl daemon-reload"); err != nil {
			return result, rollback(fmt.Errorf("reload systemd: %w", err))
		}
		result.Reloaded = true
	}
	if plan.Restart {
		if _, err := runner.RunRootContext(ctx, "systemctl enable containerd >/dev/null && systemctl restart containerd"); err != nil {
			return result, rollback(fmt.Errorf("restart containerd: %w", err))
		}
		result.Restarted = true
	} else if _, err := runner.RunRootContext(ctx, "systemctl is-active --quiet containerd || systemctl start containerd"); err != nil {
		return result, rollback(fmt.Errorf("ensure containerd is active: %w", err))
	}

	verification, err := runner.RunRootContext(ctx, containerdCRIVerificationCommand(sandboxImage, verificationImage))
	if err != nil {
		return result, rollback(fmt.Errorf("verify containerd CRI: %w", err))
	}
	result.Verification = containerdVerificationResult(strings.TrimSpace(verification))
	switch result.Verification {
	case containerdVerifiedPulls:
	case containerdVerifiedReady:
		if requireRealPull || result.Changed {
			return result, rollback(fmt.Errorf("verify containerd CRI: crictl is unavailable; a real image pull is required after changing containerd egress"))
		}
	default:
		return result, rollback(fmt.Errorf("verify containerd CRI: unexpected result %q", result.Verification))
	}
	return result, nil
}
