package deploy

import "fmt"

const generatedRegistryHostsMarker = "# Generated by CasOS"

// GenerateContainerdConfig returns the content for /etc/containerd/config.toml.
// For containerd 2.x the registry mirrors are configured via a hosts-dir;
// use GenerateDockerHubHostsToml / GenerateK8sRegistryHostsToml for those files.
func GenerateContainerdConfig(sandboxImage string) string {
	return fmt.Sprintf(`# Generated by CasOS
version = 2

[plugins.'io.containerd.cri.v1.images']
  [plugins.'io.containerd.cri.v1.images'.pinned_images]
    sandbox = %q

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc.options]
  SystemdCgroup = true

[plugins.'io.containerd.cri.v1.images'.registry]
  config_path = '/etc/containerd/certs.d'
`, sandboxImage)
}

// GenerateDockerHubHostsToml returns the content for
// /etc/containerd/certs.d/docker.io/hosts.toml. The canonical server remains
// the fallback when the mirror is unavailable.
func GenerateDockerHubHostsToml() string {
	return generatedRegistryHostsMarker + `
server = "https://registry-1.docker.io"

[host."https://docker.1ms.run"]
  capabilities = ["pull", "resolve"]
`
}

// GenerateK8sRegistryHostsToml returns the content for
// /etc/containerd/certs.d/registry.k8s.io/hosts.toml. The canonical server
// remains the fallback when the mirror is unavailable.
func GenerateK8sRegistryHostsToml() string {
	return generatedRegistryHostsMarker + `
server = "https://registry.k8s.io"

[host."https://k8s.m.daocloud.io"]
  capabilities = ["pull", "resolve"]
`
}

// GenerateGhcrHostsToml returns the content for
// /etc/containerd/certs.d/ghcr.io/hosts.toml. The canonical server remains the
// fallback when the mirror is unavailable.
func GenerateGhcrHostsToml() string {
	return generatedRegistryHostsMarker + `
server = "https://ghcr.io"

[host."https://ghcr.nju.edu.cn"]
  capabilities = ["pull", "resolve"]
`
}

func legacyDockerHubHostsToml() string {
	return `server = "https://registry-1.docker.io"

[host."https://docker.1ms.run"]
  capabilities = ["pull", "resolve"]
`
}

func legacyK8sRegistryHostsToml() string {
	return `server = "https://registry.k8s.io"

[host."https://registry.aliyuncs.com/google_containers"]
  capabilities = ["pull", "resolve"]
`
}
