package server

import "fmt"

// GenerateContainerdConfig returns the content for /etc/containerd/config.toml.
func GenerateContainerdConfig(sandboxImage, socks5Proxy string) string {
	return fmt.Sprintf(`# Generated by CasOS
version = 2

[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = %q
`, sandboxImage)
}
