appname       = casos
httpport      = 9000
runmode       = dev
SessionOn     = true
copyrequestbody = true

driverName    = mysql
dataSourceName= root:123456@tcp(mysql:3306)/
dbName        = casos_ci

casdoorEndpoint     = https://door.casdoor.com
clientId            = ci
clientSecret        = ci
casdoorOrganization = casos
casdoorApplication  = ci

apiserverPort = 6443
apiserverBind = 127.0.0.1
dataDir       = /var/lib/casos

managedNodeSecretKey = ci-managed-node-secret
